# https://leetcode.com/problems/lexicographically-smallest-generated-string

class Solution:
    """3474. Lexicographically Smallest Generated String
    
    You are given two strings, str1 and str2, of lengths n and m,
    respectively. A string word of length n + m - 1 is defined to be
    generated by str1 and str2 if it satisfies the following conditions
    for each index 0 <= i <= n - 1: If str1[i] == 'T', the substring
    of word with size m starting at index i is equal to str2, i.e.,
    word[i..(i + m - 1)] == str2. If str1[i] == 'F', the substring
    of word with size m starting at index i is not equal to str2, i.e.,
    word[i..(i + m - 1)] != str2. Return the lexicographically
    smallest possible string that can be generated by str1 and str2. If
    no string can be generated, return an empty string "".
    """
    def generate_string(self, str1: str, str2: str) -> str:
        n = len(str1)
        m = len(str2)
        # ans holds characters; initially "?" for unfixed positions
        ans = ["?"] * (n + m - 1)
        # fixed tracks positions forced by any 'T'
        fixed = [False] * (n + m - 1)
        # apply all 'T' constraints and detect conflicts
        for i in range(n):
            if str1[i] == "T":
                for j in range(m):
                    if fixed[i + j] and ans[i + j] != str2[j]:
                        return ""
                    ans[i + j] = str2[j]
                    fixed[i + j] = True
        # any 'F' already forced to full match is impossible
        for i in range(n):
            if str1[i] == "F":
                if "".join(ans[i:i + m]) == str2:
                    return ""
        # set every unfixed position to 'a' (lex smallest default)
        for i in range(len(ans)):
            if ans[i] == "?":
                ans[i] = "a"
        # fix each violated 'F' (now possible only via free 'a' positions)
        # by changing its rightmost unfixed position to 'b'
        # (guaranteed != because violated implies str2 char was 'a' there)
        for i in range(n):
            if str1[i] == "F":
                if "".join(ans[i:i + m]) == str2:
                    for j in range(m - 1, -1, -1):
                        if not fixed[i + j]:
                            ans[i + j] = "b"
                            break
        return "".join(ans)

    generateString = generate_string