# https://leetcode.com/problems/find-the-difference/


class Solution:
    """389. Find the Difference

    You are given two strings `s` and `t`.

    String `t` is generated by random shuffling string `s` and then add one more letter at a
    random position.

    Return the letter that was added to `t`.
    """

    def findTheDifference(self, s: str, t: str) -> str:
        ...
