[project]
name = "leetcode-dailies"
version = "0.0.1"
description = "yyolk's daily leetcode.com solutions"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "markdownify",
    "black",
    "BeautifulSoup4",
    "gql[aiohttp]",
]

# not the best way to declare, it's also not a 'proper' entrypoint
[project.scripts]
generate-active-daily = "generate_active_daily:__main__"
generate-calendar-toc = "genearte_calendar_toc:__main__"

[tool.pylint."messages control"]
disable = ["unspecified-encoding"]

[tool.black]
line-length = 88
