# https://leetcode.com/problems/find-the-difference/
from collections import Counter


class Solution:
    """389. Find the Difference

    You are given two strings `s` and `t`.

    String `t` is generated by random shuffling string `s` and then add one more letter at a
    random position.

    Return the letter that was added to `t`.
    """

    def findTheDifference(self, s: str, t: str) -> str:
        """Finds the one character difference between two input strings

        Proposed solution using Counter subtraction.

        Args:
            s (str): input s
            t (str): input t, one character off, with shuffled letters from s

        Returns:
            str: the one character that is different
        """
        # Create counters, counting all letters in each string
        count_s = Counter(s)
        count_t = Counter(t)

        # Subtract count_s from count_t, the letter left is the letter that's different
        return list((count_t - count_s).keys())[0]
