name: Run Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version-file: pyproject.toml
    - name: Run tests
      run: uv run --no-project --with pytest --with pytest-asyncio --with pytest-xdist python -m pytest tests/ -n auto --dist loadfile -v
